CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	REPLY_ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	USER_ID NUMBER NOT NULL,
	BOARD_ID NUMBER NOT NULL,
	REPLY_GROUP NUMBER NOT NULL,
	REPLY_DEPTH NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BOARD_ID) REFERENCES TBL_BOARD(BOARD_ID) ON DELETE CASCADE
);

SELECT * FROM TBL_REPLY;